"""
Django settings for WALD project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import posixpath
import socket
from django.contrib import admin

# Get the HOST by IP address
hst = socket.gethostbyname(socket.gethostname())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../../writable/database/"))
MEDIA_ROOT = os.path.abspath(os.path.join(BASE_DIR, "../../writable/media/"))
if "RU-wbd\\writable" in WRITABLE_DIR:
    # Need another string
    WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../../../writable/database/"))
    MEDIA_ROOT = os.path.abspath(os.path.join(BASE_DIR, "../../../writable/media/"))

APP_PREFIX = "dd/"
ADMIN_SITE_URL = ""
if "d:" in WRITABLE_DIR or "D:" in WRITABLE_DIR:
    APP_PREFIX = ""
    DEBUG = True
elif "/scratch" in WRITABLE_DIR or "/var/www" in WRITABLE_DIR or "131.174" in hst:
    # Configuration for http://ewald.science.ru.nl/
    # Also works for http://e-wald.nl
    APP_PREFIX = ""
    ADMIN_SITE_URL = '/'
else:
    APP_PREFIX = "ewald/"
    ADMIN_SITE_URL = '/ewald'


# Not the location of the wsgi.py file for "reload_wald"
WSGI_FILE = os.path.abspath(os.path.join(BASE_DIR,"wald/wsgi.py"))

# publishing on a sub-url
# NOTE: possibly remove this for the production environment...
# FORCE_SCRIPT_NAME = admin.site.site_url


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '485c409a-daf7-47d3-81af-257049728c58'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'e-wald.science.ru.nl',
                 'e-wald.nl', 'www.e-wald.nl']
CSRF_TRUSTED_ORIGINS = ['https://e-wald.nl']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # The apps for RU-wald
    'wald.dictionary',
    'wald.mapview',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wald.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'wald/templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # =========== THIS IS CACHED LOADING ====================
            #'loaders': [
            #    ('django.template.loaders.cached.Loader', [
            #        'django.template.loaders.filesystem.Loader',
            #        'django.template.loaders.app_directories.Loader',
            #    ]),
            #],
            # =======================================================
            'debug': DEBUG,
        },
        'APP_DIRS': True, # This cannot co-occur with 'loaders' in Django 1.9
    },
]

WSGI_APPLICATION = 'wald.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(WRITABLE_DIR, 'wald.db'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Amsterdam'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
if ("/scratch" in WRITABLE_DIR or "ewald" in APP_PREFIX):
    STATIC_URL = '/'+APP_PREFIX+'static/'
    MEDIA_URL = "/" + APP_PREFIX + "media/"

# STATIC_ROOT = posixpath.join(*(BASE_DIR.split(os.path.sep) + ['static']))
# The following should be better:
STATIC_ROOT = os.path.abspath(os.path.join("/", posixpath.join(*(BASE_DIR.split(os.path.sep) + ['static']))))
